### ISSUE TITLE
Sample documentation for IoT Jobs

### ISSUE THREAD

**Issue by madhu-korada** [aws/aws-iot-device-sdk-cpp-v2#355] opened 2021-11-24 20:51 UTC
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on - Ubuntu 16.04

**Describe the question**
I am trying to use IoT Jobs Service, I was able to run the sample which was given in the sample folder. But I want to do more than just describe as given in the sample. I used the update related functions as per the documentation. But there seems to be this error `Service Error 2 occurred`. I saw in the file `RejectedErrorCode.cpp` that 2 stands for `RejectedErrorCode::InvalidRequest` I guess. I can't seem to figure out where the issue lies. I am having to spend a lot of time trying to make a sample PoC, any help would be appreciated. 

Is there any simplified documentation for these error codes so that development would be a little faster? 
Furthermore, Is there any sample implemented for update related functions?

**Comment by madhu-korada** [comment] 2021-11-24 21:18
This is what my code looks like. 
```
        IotJobsClient client(demo.connection);

        UpdateJobExecutionSubscriptionRequest updateJobExecutionSubscriptionRequest;
        updateJobExecutionSubscriptionRequest.ThingName = demo.thingName;
        updateJobExecutionSubscriptionRequest.JobId = demo.jobId;

        // This isn't absolutely necessary but since we're doing a publish almost immediately afterwards,
        // to be cautious make sure the subscribe has finished before doing the publish.
        std::promise<void> subAckedPromise;
        auto subAckHandler = [&](int) {
            /* if error code returns it will be recorded by the other callback */
            subAckedPromise.set_value();
        };

        auto subscriptionHandler = [&](UpdateJobExecutionResponse *response, int ioErr) {
            if (ioErr)
            {
                fprintf(stderr, "!!!!!!!!!!!!!!!!!!!!!!!\n");
                fprintf(stderr, "Error %d occurred\n", ioErr);
                return;
            }
            fprintf(stdout, "Received Job !!!!!!!!!!!!!!!!!!!!!!!\n");
        };


        client.SubscribeToUpdateJobExecutionAccepted(
            updateJobExecutionSubscriptionRequest, AWS_MQTT_QOS_AT_LEAST_ONCE, subscriptionHandler, subAckHandler);
        subAckedPromise.get_future().wait();
        
        subAckedPromise = std::promise<void>();
        auto failureHandler = [&](RejectedError *rejectedError, int ioErr) {
            if (ioErr)
            {
                fprintf(stderr, "Error %d occurred\n", ioErr);
                return;
            }

            if (rejectedError)
            {
                fprintf(stderr, "Service Error %d occurred\n", (int)rejectedError->Code.value());
                return;
            }
        };

        client.SubscribeToUpdateJobExecutionRejected(
            updateJobExecutionSubscriptionRequest, AWS_MQTT_QOS_AT_LEAST_ONCE, failureHandler, subAckHandler);
        subAckedPromise.get_future().wait();

        UpdateJobExecutionRequest updateJobExecutionRequest;
        updateJobExecutionRequest.ThingName = demo.thingName;
        // updateJobExecutionRequest.IncludeJobExecutionState = true;
        updateJobExecutionRequest.JobId = demo.jobId;
        // updateJobExecutionRequest.IncludeJobDocument = true;
        // updateJobExecutionRequest.ExecutionNumber = 1;
        updateJobExecutionRequest.Status = Aws::Iotjobs::JobStatus::SUCCEEDED;
        Aws::Crt::UUID uuid;
        updateJobExecutionRequest.ClientToken = uuid.ToString();
        std::promise<void> publishUpdateJobExeCompletedPromise;

        auto publishHandler = [&](int ioErr) {
            if (ioErr)
            {
                fprintf(stderr, "Error %d occurred\n", ioErr);
            }
            fprintf(stdout, "!!!!!!!!!!!!!!!!!!!!!!!\n");
            fprintf(stdout, "Inside Publish Handler \n");
            publishUpdateJobExeCompletedPromise.set_value();
            fprintf(stdout, "After set_value in Publish Handler \n");
        };

        client.PublishUpdateJobExecution(
            std::move(updateJobExecutionRequest), AWS_MQTT_QOS_AT_LEAST_ONCE, publishHandler);
        publishUpdateJobExeCompletedPromise.get_future().wait();

```

**Comment by madhu-korada** [comment] 2021-11-24 22:00
As per the [documentation](https://docs.aws.amazon.com/iot/latest/developerguide/jobs-devices.html) using jobId`$next` can be used instead of the name of the job. When I am replacing $next with my job name I am not facing the above-mentioned issue. What are the cases the $next does not work as it should?

**Comment by jmklix** [comment] 2021-12-03 23:30
Closing this issue as it appears to be a duplicate of this [issue](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/357).

**Closed by jmklix** 2021-12-03 23:30 UTC
Labels: guidance, needs-triage
