### ISSUE TITLE
packets are not getting published after connection interruption on macos

### ISSUE THREAD

**Issue by elad-ep** [aws/aws-iot-device-sdk-cpp-v2#138] opened 2020-07-30 05:49 UTC
Hi, we upgraded to v1.7.2 with x509 credentials provider support. we have an issue on mac os - after disconnecting network, packets are not getting published anymore even after network connection is resumed. keepAliveTimeSecs (in Connect() API) is set to 300 (5 minutes). attached log. this is the timeline:

14:03 - network is off
14:24 - network is on
15:33 - end of log

since network is off (even after it was resumed) packets are not getting published. onPublishComplete callback is not called for the packets (not even with an error return code). OnConnectionInterrupted and OnConnectionResumed callbacks are not invoked (I would expect invocation after 5 min. due to the keep alive time).

Thanks

[awssdk.zip](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/4999052/awssdk.zip)

**Comment by elad-ep** [comment] 2020-08-03 14:32
Hi, can you please review the log? do you need any additional information? please note that this issue is specific to mac - we don't have similar issue on Windows when using the  x509 credentials provider. thanks

**Comment by TingDaoK** [comment] 2020-08-06 00:25
Hi @elad-ep 

I checked out at the log file. The log file shows even after 14:24, the timeout still happens to PINGREQ, which means the reconnect is not succeed. Was the on_interrupt callback invoked? How did you turn off the network? The log also shows the client side didn't detect the lost of connection at all, which means client never attempt to reconnect.

And, can you try again with the latest version? We just updated the dependency for some fix, which may solve the onPublishComplete not invoked problem.

**Comment by elad-ep** [comment] 2020-08-06 06:54
network is turned off using "Turn Wi-Fi off" option in mac menu bar (https://support.apple.com/en-us/HT201974). we are using the latest released version (v1.7.2). does the onPublishComplete fix you talk about is in master and not in v1.7.2? anyway, I assume it won't explain why the SDK fails to detect the network disconnection...? (on_interrupt callback is not invoked)

**Comment by TingDaoK** [comment] 2020-08-06 17:09
Right, I forgot to cut a new release... Now, the new release is out.

I'm not sure what happened, but I cannot reproduce it with the normal credential files on Mac... I'll try to use x509 credentials provider later to see if I can reproduce the issue.

**Comment by elad-ep** [comment] 2020-08-06 17:26
indeed - the sdk doesn't recognize the network status change as you said. please try with "Turn Wi-Fi off" option when you test. thanks

**Comment by TingDaoK** [comment] 2020-08-07 00:03
Hi @elad-ep,

I still cannot reproduce the issue, but the log information provides some clues about what happened. 

Can you try to set keepAliveTimeSecs to much shorter? Like 10 secs, and make sure your internet lost longer than that.

Based on the log information, we proposed a possible fix for it, but since I cannot reproduce the issue, can you try pull the fix branch and try again to see if it sovles the issue? To do that, make sure you have the lastest version of aws-iot-device-sdk-cpp-v2. In you aws-iot-device-sdk-cpp-v2 dir, run commands like:
``` sh
cd aws-common-runtime/aws-crt-cpp/aws-common-runtime/aws-c-http/
git pull
git checkout -b origin/websocket-close-timeout
```
And rebuild the project. Please try this fix, and if it fixes your issue, we will get the fix published. If not, please let me know.

Thank you!

**Comment by elad-ep** [comment] 2020-08-07 06:01
thanks! I will test this branch. do you want to add more logging before I test the branch, so in case it doesn't work you'll have enough logging to track the issue?

**Comment by TingDaoK** [comment] 2020-08-07 06:26
Thank you! I have added more trace-level logs to that branch. BTW, the commands I provided was wrong... Should be:
```sh
cd aws-common-runtime/aws-crt-cpp/aws-common-runtime/aws-c-http/
git pull
git checkout -b websocket-close-timeout origin/websocket-close-timeout
```

**Comment by elad-ep** [comment] 2020-08-10 14:59
The sdk crashes after turning off the network:

`0x000000010f89502f s_channel_task_run + 31
0x000000010f86ca51 aws_task_scheduler_cancel_task + 177
0x000000010f89495c s_on_shutdown_completion_task + 76
0x000000010f86c69c s_run_all + 348
0x000000010f8928f7 s_event_thread_main + 1863
0x000000010f86aaa8 thread_fn + 88
0x00007fff6a0db109 _pthread_start + 148
0x00007fff6a0d6b8b thread_start + 15`

attached log. crash happens at 13:58:21. thanks

[awssdk.log](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/5051579/awssdk.log)

**Comment by TingDaoK** [comment] 2020-08-10 16:57
Okay, so sorry that it was my mistake... I updated the branch and it should be good now.

**Comment by elad-ep** [comment] 2020-08-10 18:29
build doesn't compile now, I pull latest changes:

Scanning dependencies of target aws-c-http
[ 34%] Building C object aws-common-runtime/aws-crt-cpp/aws-common-runtime/aws-c-http/CMakeFiles/aws-c-http.dir/source/connection.c.o
/aws-iot-device-sdk-cpp-v2/aws-common-runtime/aws-crt-cpp/aws-common-runtime/aws-c-http/source/connection.c:911:17: error: implicit
      declaration of function 'aws_string_new_from_cursor' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    host_name = aws_string_new_from_cursor(options.allocator, &options.host_name);
                ^
/aws-iot-device-sdk-cpp-v2/aws-common-runtime/aws-crt-cpp/aws-common-runtime/aws-c-http/source/connection.c:911:17: note: did you mean
      'aws_string_new_from_c_str'?
/aws-iot-device-sdk-cpp-v2/aws-common-runtime/aws-crt-cpp/aws-common-runtime/aws-c-common/include/aws/common/string.h:102:20: note: 
      'aws_string_new_from_c_str' declared here
struct aws_string *aws_string_new_from_c_str(struct aws_allocator *allocator, const char *c_str);
                   ^
/aws-iot-device-sdk-cpp-v2/aws-common-runtime/aws-crt-cpp/aws-common-runtime/aws-c-http/source/connection.c:911:15: error: 
      incompatible integer to pointer conversion assigning to 'struct aws_string *' from 'int' [-Werror,-Wint-conversion]
    host_name = aws_string_new_from_cursor(options.allocator, &options.host_name);
              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [aws-common-runtime/aws-crt-cpp/aws-common-runtime/aws-c-http/CMakeFiles/aws-c-http.dir/source/connection.c.o] Error 1
make[1]: *** [aws-common-runtime/aws-crt-cpp/aws-common-runtime/aws-c-http/CMakeFiles/aws-c-http.dir/all] Error 2
make: *** [all] Error 2

**Comment by TingDaoK** [comment] 2020-08-10 19:10
the dependency updated... Let's do a more formal way, I'll get a new release for aws-crt-cpp, which should fix the problem. Or you can try to update aws-c-common to the lastest. I'll let you know once the release is out

**Comment by elad-ep** [comment] 2020-08-10 19:30
I'm not sure what changed by I'm getting git errors now. I deleted my repository and started fresh:
```
cd aws-common-runtime/aws-crt-cpp/aws-common-runtime/aws-c-http/
git pull
git checkout -b websocket-close-timeout origin/websocket-close-timeout
```

getting:
`fatal: 'origin/websocket-close-timeout' is not a commit and a branch 'websocket-close-timeout' cannot be created from it`

**Comment by TingDaoK** [comment] 2020-08-10 19:37
Oh, i just merged it to master, so the branch is deleted. The problem now is you still need update the aws-c-common. If you want, you can do
```
cd aws-common-runtime/aws-crt-cpp/aws-common-runtime/aws-c-http/
git pull
git checkout master
git pull

# from aws-c-http/
cd ../aws-c-common/
git checkout master
git pull
```

**Comment by elad-ep** [comment] 2020-08-10 19:40
or I can just re-clone the master repository and everything is there, right?
`git clone --recursive https://github.com/aws/aws-iot-device-sdk-cpp-v2.git`

**Comment by TingDaoK** [comment] 2020-08-10 19:42
Not now... I am still working on the release process. Something is blocked... Probably need about an hour... I'll update here once the release is updated

**Comment by TingDaoK** [comment] 2020-08-10 20:05
Okay, things went fater than I thougt. The master branch is now updated. You can re-clone it now
`git clone --recursive https://github.com/aws/aws-iot-device-sdk-cpp-v2.git`

**Comment by TingDaoK** [comment] 2020-08-10 20:11
Or you can just do the following:
```
under aws-iot-device-sdk-cpp-v2/
git checkout master
git pull
git submodule update --init --recursive
```

**Comment by elad-ep** [comment] 2020-08-11 13:54
The issue is resolved with current master, thanks!! can you please cut a new release version?

**Comment by TingDaoK** [comment] 2020-08-11 16:06
Great! The new release is out! Thank you!

**Closed by TingDaoK** 2020-08-11 16:06 UTC
Labels: bug
